services:
  - type: web
    name: A.L.M.A.N.A.C
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install -r requirements.txt
    startCommand: python server.py
